server:
  port: 2000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb_spring?useSSL=false
    username: root
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: update

# App Properties
application:
  sec:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 60000 #3600000
    jwtRefreshExpirationMs: 120000 #86400000